### ISSUE TITLE
gta not working

### ISSUE THREAD

**Issue by harel091** [WarenGonzaga/wrn-cleaner#19]
### 🤔 Not Existing Bug?

- [X] Yes, I'm sure that this is a bug!

### 👀 Current Behavior

its crashing me rn after that shit i dids

### 🎯 Expected Behavior

s

### 📋 Steps To Reproduce

asfffds

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/warengonzaga/wrn-cleaner/blob/main/CODE_OF_CONDUCT.md).

**Comment by warengonzaga** [comment]
I'm closing this as you didn't provide the necessary information about what you are experiencing.
